package com.ouag.demo.config

import com.ouag.demo.DemoController
import org.springframework.boot.autoconfigure.{EnableAutoConfiguration, ImportAutoConfiguration}
import org.springframework.context.annotation.{Bean, Configuration}


@Configuration
@ImportAutoConfiguration(Array(classOf[org.springframework.boot.actuate.autoconfigure.amqp.RabbitHealthContributorAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.audit.AuditAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.audit.AuditEventsEndpointAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.availability.AvailabilityHealthContributorAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.availability.AvailabilityProbesAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.beans.BeansEndpointAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.cache.CachesEndpointAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.cassandra.CassandraHealthContributorAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.cassandra.CassandraReactiveHealthContributorAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.cloudfoundry.servlet.CloudFoundryActuatorAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.cloudfoundry.reactive.ReactiveCloudFoundryActuatorAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.condition.ConditionsReportEndpointAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.context.properties.ConfigurationPropertiesReportEndpointAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.context.ShutdownEndpointAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.couchbase.CouchbaseHealthContributorAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.couchbase.CouchbaseReactiveHealthContributorAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.elasticsearch.ElasticSearchReactiveHealthContributorAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.elasticsearch.ElasticSearchRestHealthContributorAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.endpoint.EndpointAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.endpoint.jmx.JmxEndpointAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.endpoint.web.WebEndpointAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.env.EnvironmentEndpointAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.flyway.FlywayEndpointAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.hazelcast.HazelcastHealthContributorAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.health.HealthContributorAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.health.HealthEndpointAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.influx.InfluxDbHealthContributorAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.info.InfoContributorAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.info.InfoEndpointAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.integration.IntegrationGraphEndpointAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.jdbc.DataSourceHealthContributorAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.jms.JmsHealthContributorAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.ldap.LdapHealthContributorAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.liquibase.LiquibaseEndpointAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.logging.LogFileWebEndpointAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.logging.LoggersEndpointAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.mail.MailHealthContributorAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.management.HeapDumpWebEndpointAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.management.ThreadDumpEndpointAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.metrics.CompositeMeterRegistryAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.metrics.JvmMetricsAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.metrics.KafkaMetricsAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.metrics.Log4J2MetricsAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.metrics.LogbackMetricsAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.metrics.MetricsAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.metrics.MetricsEndpointAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.metrics.SystemMetricsAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.metrics.amqp.RabbitMetricsAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.metrics.cache.CacheMetricsAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.metrics.data.RepositoryMetricsAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.metrics.export.appoptics.AppOpticsMetricsExportAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.metrics.export.atlas.AtlasMetricsExportAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.metrics.export.datadog.DatadogMetricsExportAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.metrics.export.dynatrace.DynatraceMetricsExportAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.metrics.export.elastic.ElasticMetricsExportAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.metrics.export.ganglia.GangliaMetricsExportAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.metrics.export.graphite.GraphiteMetricsExportAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.metrics.export.humio.HumioMetricsExportAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.metrics.export.influx.InfluxMetricsExportAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.metrics.export.jmx.JmxMetricsExportAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.metrics.export.kairos.KairosMetricsExportAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.metrics.export.newrelic.NewRelicMetricsExportAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.metrics.export.prometheus.PrometheusMetricsExportAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.metrics.export.signalfx.SignalFxMetricsExportAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.metrics.export.simple.SimpleMetricsExportAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.metrics.export.stackdriver.StackdriverMetricsExportAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.metrics.export.statsd.StatsdMetricsExportAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.metrics.export.wavefront.WavefrontMetricsExportAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.metrics.jdbc.DataSourcePoolMetricsAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.metrics.mongo.MongoMetricsAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.metrics.r2dbc.ConnectionPoolMetricsAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.metrics.web.client.HttpClientMetricsAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.metrics.web.jetty.JettyMetricsAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.metrics.web.reactive.WebFluxMetricsAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.metrics.web.servlet.WebMvcMetricsAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.metrics.web.tomcat.TomcatMetricsAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.mongo.MongoHealthContributorAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.mongo.MongoReactiveHealthContributorAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.neo4j.Neo4jHealthContributorAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.quartz.QuartzEndpointAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.r2dbc.ConnectionFactoryHealthContributorAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.redis.RedisHealthContributorAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.redis.RedisReactiveHealthContributorAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.scheduling.ScheduledTasksEndpointAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.security.reactive.ReactiveManagementWebSecurityAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.session.SessionsEndpointAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.solr.SolrHealthContributorAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.startup.StartupEndpointAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.system.DiskSpaceHealthContributorAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.trace.http.HttpTraceAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.trace.http.HttpTraceEndpointAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.web.mappings.MappingsEndpointAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.web.reactive.ReactiveManagementContextAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.web.server.ManagementContextAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.web.servlet.ServletManagementContextAutoConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.endpoint.web.ServletEndpointManagementContextConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.endpoint.web.reactive.WebFluxEndpointManagementContextConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.endpoint.web.servlet.WebMvcEndpointManagementContextConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.security.servlet.SecurityRequestMatchersManagementContextConfiguration],
  classOf[org.springframework.boot.actuate.autoconfigure.web.reactive.ReactiveManagementChildContextConfiguration]))
class ControllerConfiguration {

  //  @Bean def demoController: DemoController = new DemoController


}
